# -*- coding: utf-8 -*-
"""latihan DAA minggu 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Od5jJga8aAi78Q-w1LE7p-UmTRnMymCM
"""

nama = input("nama anda: ")
nim = input("NIM anda: ")
del print
print("nama anda adalah" , nama)
print("nim anda adalah" , nim)

myList = [1, 2, 3, 4, 5]
getSum = sum(myList)
print(getSum)

myList = [1, 2, 3, 4, 5]
getLast = myList[-1]
print(getLast)

myList = [1, 2, 3, 4, 5]
getSecond = myList[2]
print(getSecond)

def getBagi(myList, divisor):
  if divisor == 0:
    return "Tidak dapat dibagi dengan nol!"

  result = []
  for num in myList:
    result.append(num / divisor)
  return result

myList = [1, 2, 3, 4, 5]
divisor = 2
hasilBagi = getBagi(myList, divisor)
print(hasilBagi)

himpunan_angka = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]

# Define the function bagi_dua_sama_rata
def bagi_dua_sama_rata(himpunan):
  """Membagi list menjadi dua bagian sama rata."""
  tengah = len(himpunan) // 2
  return himpunan[:tengah], himpunan[tengah:]

# Membagi sama rata
bagian1, bagian2 = bagi_dua_sama_rata(himpunan_angka)
print(bagian1)  # Output: [3, 1, 4, 1, 5]
print(bagian2)  # Output: [9, 2, 6, 5, 3, 5]